### ISSUE TITLE
баг с редактированием объекта

### ISSUE THREAD

**Issue by YaregBel** [soulasphyxia/thp_project#1]
При попытке редактирования одного из объектов меняется не выбранный объект.
![image](https://github.com/soulasphyxia/thp_project/assets/90565494/23f3c9dc-fcf6-4c63-af8e-f8bb101e1eae)
![image](https://github.com/soulasphyxia/thp_project/assets/90565494/4290991d-7609-4e96-8d0e-33553f9533d2)

**Comment by soulasphyxia** [comment]
commit
